### ISSUE TITLE
NODE_ARRAY: child node: is not a node (ArgumentError)

### ISSUE THREAD

**Issue by lim-daniel** [dig386/node-marshal#2]
Error appear in 0.2.1 and 0.2.2.

Ruby version:
```
ruby 2.2.4p230 (2015-12-16 revision 53155) [armv7l-linux-eabihf]
```

Error:
```
gems/node-marshal-0.2.2/lib/node-marshal.rb:55:in `to_bin': dump_node_value, parent node NODE_ARRAY (ADR 0x79f278): child node 2 (ADR 0x1): is not a node (ArgumentError)
  Type: Fixnum (21), Value: 0
	from /home/imguser/.rvm/gems/ruby-2.2.4/gems/node-marshal-0.2.2/lib/node-marshal.rb:55:in `to_compiled_rb'
	from /home/imguser/.rvm/gems/ruby-2.2.4/gems/node-marshal-0.2.2/lib/node-marshal.rb:93:in `compile_rb_file'
	from /home/imguser/.rvm/gems/ruby-2.2.4/gems/node-marshal-0.2.2/bin/noderbc:62:in `<top (required)>'
	from /home/imguser/.rvm/gems/ruby-2.2.4/bin/noderbc:22:in `load'
	from /home/imguser/.rvm/gems/ruby-2.2.4/bin/noderbc:22:in `<main>'
	from /home/imguser/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
	from /home/imguser/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by alvoskov** [comment]
@lim-daniel, could you give some minimal example of Ruby code that causes such compilation error? NODE_ARRAY node of Ruby AST has some not very well documented features. May be something is not covered by gem tests.
